WEIXIN_TOKEN = 'itcast_wechat'
WEIXIN_APPID = 'wx63afd8910ac82737'
WEIXIN_APPSECRET = '06abca4d83a582c46a37957c4c499ba2'

WEIXIN_ACCESS_TOKEN_URL = 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=' + WEIXIN_APPID + '&secret=' + WEIXIN_APPSECRET
WEIXIN_ACCESS_TOKEN = ''
WEIXIN_ACCESS_TOKEN_LASTTIME = 0
WEIXIN_ACCESS_TOKEN_EXPIRES_IN = 0